name: Scrape Stocks | Upload to Firebase

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use a stable version of Node.js (16 or 18)

      - name: Install dependencies
        run: npm install

      - name: Install Chromium for Puppeteer
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          sudo apt-get install -y chromium-browser libx11-dev libx11-xcb-dev libglu1-mesa libglib2.0-0 libnss3 libxcomposite1 libxdamage1 libxrandr2 libatk1.0-0 libatk-bridge2.0-0 libappindicator3-1 libgdk-pixbuf2.0-0 libnspr4 libnss3

      - name: Run scraper
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: |
          # Set the executable path for Puppeteer to use Chromium
          export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
          node scraper.js
