name: Scrape and Upload to Firebase

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Cache Chromium
        uses: actions/cache@v2
        with:
          path: /usr/bin/chromium-browser
          key: ${{ runner.os }}-chromium-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-chromium-

      - name: Install Chromium for Puppeteer if not cached
        run: |
          if [ ! -f /usr/bin/chromium-browser ]; then
            sudo apt-get update -y
            sudo apt-get install -y chromium-browser
          fi

      - name: Run scraper
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        run: |
          node scraper.js
